---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: db
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: db
  name: allow-port-forward
rules:
- apiGroups: [""]
  resources: ["pods", "pods/portforward"]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-port-forward
  namespace: db
subjects:
- kind: ServiceAccount
  name: developer
roleRef:
  kind: Role
  name: allow-port-forward
  apiGroup: rbac.authorization.k8s.io
